[project]
name = "c-d-e"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anis", email = "kaarthianis27@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "faker>=40.36.0",
    "numpy>=2.5.2",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
c-d-e = "c_d_e:main"

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
